version: '3.9'

services:
  backend:
    container_name: compose-back-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: compose-backend-image
    networks:
      - backend
    ports:
      - 4000:3001
    env_file:
      - .env
    depends_on:
      - postgres
    restart: "unless-stopped"

  frontend:
    container_name: compose-front-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - frontend
    image: compose-frontend-image
    ports:
      - 3005:80
    restart: "unless-stopped"

  postgres:
    container_name: postgres
    image: postgres
    networks:
      - backend
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - .env
    restart: "unless-stopped"

  adminer:
    networks:
      - backend
    container_name: adminer
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - postgres

networks:
  frontend:
  backend:

volumes:
  postgres_data:
